# Generated by Django 4.0.4 on 2022-05-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userFirstName', models.CharField(max_length=30)),
                ('userLastName', models.CharField(max_length=30)),
                ('userMail', models.EmailField(max_length=100)),
                ('userAddress', models.CharField(max_length=30)),
                ('userAge', models.IntegerField()),
                ('registrationDate', models.DateTimeField(auto_now=True)),
                ('isMajor', models.BooleanField()),
            ],
        ),
    ]
