# Generated by Django 4.0.4 on 2022-05-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userAddress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userAge',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userFirstName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userLastName',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userMail',
            new_name='Mail',
        ),
    ]
