# Generated by Django 4.0.4 on 2022-05-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_useraddress_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Mail',
            new_name='mail',
        ),
    ]
