# Generated by Django 4.0.4 on 2022-05-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_address_user_address_rename_age_user_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
