# Generated by Django 4.0.4 on 2022-05-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('JavaScript', 'Javascript'), ('C++', 'Cplus'), ('C#', 'Csharp'), ('Python', 'Python'), ('PHP', 'Php'), ('None', 'None')], default='None', max_length=15),
        ),
    ]
