# Generated by Django 4.0.4 on 2022-05-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='participant',
        ),
    ]
