# Generated by Django 4.0.4 on 2022-05-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rename_user_project_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='participant',
            new_name='user',
        ),
    ]
