# Generated by Django 4.0.4 on 2022-05-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_project_user_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ForeignKey(default='No project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.project'),
        ),
    ]
