# Generated by Django 4.0.4 on 2022-05-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_user_language_alter_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('JavaScript', 'Javascript'), ('C++', 'Cplus'), ('C#', 'Csharp'), ('Python', 'Python'), ('PHP', 'Php'), ('None', 'None')], default='----', max_length=15, null=True),
        ),
    ]
